package com.info.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ActivityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table a_activity
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table a_activity
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table a_activity
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_activity
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public ActivityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_activity
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_activity
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_activity
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_activity
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_activity
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_activity
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_activity
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_activity
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_activity
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a_activity
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table a_activity
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAIdIsNull() {
            addCriterion("a_id is null");
            return (Criteria) this;
        }

        public Criteria andAIdIsNotNull() {
            addCriterion("a_id is not null");
            return (Criteria) this;
        }

        public Criteria andAIdEqualTo(Integer value) {
            addCriterion("a_id =", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdNotEqualTo(Integer value) {
            addCriterion("a_id <>", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdGreaterThan(Integer value) {
            addCriterion("a_id >", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("a_id >=", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdLessThan(Integer value) {
            addCriterion("a_id <", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdLessThanOrEqualTo(Integer value) {
            addCriterion("a_id <=", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdIn(List<Integer> values) {
            addCriterion("a_id in", values, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdNotIn(List<Integer> values) {
            addCriterion("a_id not in", values, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdBetween(Integer value1, Integer value2) {
            addCriterion("a_id between", value1, value2, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdNotBetween(Integer value1, Integer value2) {
            addCriterion("a_id not between", value1, value2, "aId");
            return (Criteria) this;
        }

        public Criteria andAUseridIsNull() {
            addCriterion("a_userid is null");
            return (Criteria) this;
        }

        public Criteria andAUseridIsNotNull() {
            addCriterion("a_userid is not null");
            return (Criteria) this;
        }

        public Criteria andAUseridEqualTo(Integer value) {
            addCriterion("a_userid =", value, "aUserid");
            return (Criteria) this;
        }

        public Criteria andAUseridNotEqualTo(Integer value) {
            addCriterion("a_userid <>", value, "aUserid");
            return (Criteria) this;
        }

        public Criteria andAUseridGreaterThan(Integer value) {
            addCriterion("a_userid >", value, "aUserid");
            return (Criteria) this;
        }

        public Criteria andAUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("a_userid >=", value, "aUserid");
            return (Criteria) this;
        }

        public Criteria andAUseridLessThan(Integer value) {
            addCriterion("a_userid <", value, "aUserid");
            return (Criteria) this;
        }

        public Criteria andAUseridLessThanOrEqualTo(Integer value) {
            addCriterion("a_userid <=", value, "aUserid");
            return (Criteria) this;
        }

        public Criteria andAUseridIn(List<Integer> values) {
            addCriterion("a_userid in", values, "aUserid");
            return (Criteria) this;
        }

        public Criteria andAUseridNotIn(List<Integer> values) {
            addCriterion("a_userid not in", values, "aUserid");
            return (Criteria) this;
        }

        public Criteria andAUseridBetween(Integer value1, Integer value2) {
            addCriterion("a_userid between", value1, value2, "aUserid");
            return (Criteria) this;
        }

        public Criteria andAUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("a_userid not between", value1, value2, "aUserid");
            return (Criteria) this;
        }

        public Criteria andAActtimeIsNull() {
            addCriterion("a_acttime is null");
            return (Criteria) this;
        }

        public Criteria andAActtimeIsNotNull() {
            addCriterion("a_acttime is not null");
            return (Criteria) this;
        }

        public Criteria andAActtimeEqualTo(Date value) {
            addCriterion("a_acttime =", value, "aActtime");
            return (Criteria) this;
        }

        public Criteria andAActtimeNotEqualTo(Date value) {
            addCriterion("a_acttime <>", value, "aActtime");
            return (Criteria) this;
        }

        public Criteria andAActtimeGreaterThan(Date value) {
            addCriterion("a_acttime >", value, "aActtime");
            return (Criteria) this;
        }

        public Criteria andAActtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("a_acttime >=", value, "aActtime");
            return (Criteria) this;
        }

        public Criteria andAActtimeLessThan(Date value) {
            addCriterion("a_acttime <", value, "aActtime");
            return (Criteria) this;
        }

        public Criteria andAActtimeLessThanOrEqualTo(Date value) {
            addCriterion("a_acttime <=", value, "aActtime");
            return (Criteria) this;
        }

        public Criteria andAActtimeIn(List<Date> values) {
            addCriterion("a_acttime in", values, "aActtime");
            return (Criteria) this;
        }

        public Criteria andAActtimeNotIn(List<Date> values) {
            addCriterion("a_acttime not in", values, "aActtime");
            return (Criteria) this;
        }

        public Criteria andAActtimeBetween(Date value1, Date value2) {
            addCriterion("a_acttime between", value1, value2, "aActtime");
            return (Criteria) this;
        }

        public Criteria andAActtimeNotBetween(Date value1, Date value2) {
            addCriterion("a_acttime not between", value1, value2, "aActtime");
            return (Criteria) this;
        }

        public Criteria andAActTypeIsNull() {
            addCriterion("a_act_type is null");
            return (Criteria) this;
        }

        public Criteria andAActTypeIsNotNull() {
            addCriterion("a_act_type is not null");
            return (Criteria) this;
        }

        public Criteria andAActTypeEqualTo(Integer value) {
            addCriterion("a_act_type =", value, "aActType");
            return (Criteria) this;
        }

        public Criteria andAActTypeNotEqualTo(Integer value) {
            addCriterion("a_act_type <>", value, "aActType");
            return (Criteria) this;
        }

        public Criteria andAActTypeGreaterThan(Integer value) {
            addCriterion("a_act_type >", value, "aActType");
            return (Criteria) this;
        }

        public Criteria andAActTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("a_act_type >=", value, "aActType");
            return (Criteria) this;
        }

        public Criteria andAActTypeLessThan(Integer value) {
            addCriterion("a_act_type <", value, "aActType");
            return (Criteria) this;
        }

        public Criteria andAActTypeLessThanOrEqualTo(Integer value) {
            addCriterion("a_act_type <=", value, "aActType");
            return (Criteria) this;
        }

        public Criteria andAActTypeIn(List<Integer> values) {
            addCriterion("a_act_type in", values, "aActType");
            return (Criteria) this;
        }

        public Criteria andAActTypeNotIn(List<Integer> values) {
            addCriterion("a_act_type not in", values, "aActType");
            return (Criteria) this;
        }

        public Criteria andAActTypeBetween(Integer value1, Integer value2) {
            addCriterion("a_act_type between", value1, value2, "aActType");
            return (Criteria) this;
        }

        public Criteria andAActTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("a_act_type not between", value1, value2, "aActType");
            return (Criteria) this;
        }

        public Criteria andAActTitleIsNull() {
            addCriterion("a_act_title is null");
            return (Criteria) this;
        }

        public Criteria andAActTitleIsNotNull() {
            addCriterion("a_act_title is not null");
            return (Criteria) this;
        }

        public Criteria andAActTitleEqualTo(String value) {
            addCriterion("a_act_title =", value, "aActTitle");
            return (Criteria) this;
        }

        public Criteria andAActTitleNotEqualTo(String value) {
            addCriterion("a_act_title <>", value, "aActTitle");
            return (Criteria) this;
        }

        public Criteria andAActTitleGreaterThan(String value) {
            addCriterion("a_act_title >", value, "aActTitle");
            return (Criteria) this;
        }

        public Criteria andAActTitleGreaterThanOrEqualTo(String value) {
            addCriterion("a_act_title >=", value, "aActTitle");
            return (Criteria) this;
        }

        public Criteria andAActTitleLessThan(String value) {
            addCriterion("a_act_title <", value, "aActTitle");
            return (Criteria) this;
        }

        public Criteria andAActTitleLessThanOrEqualTo(String value) {
            addCriterion("a_act_title <=", value, "aActTitle");
            return (Criteria) this;
        }

        public Criteria andAActTitleLike(String value) {
            addCriterion("a_act_title like", value, "aActTitle");
            return (Criteria) this;
        }

        public Criteria andAActTitleNotLike(String value) {
            addCriterion("a_act_title not like", value, "aActTitle");
            return (Criteria) this;
        }

        public Criteria andAActTitleIn(List<String> values) {
            addCriterion("a_act_title in", values, "aActTitle");
            return (Criteria) this;
        }

        public Criteria andAActTitleNotIn(List<String> values) {
            addCriterion("a_act_title not in", values, "aActTitle");
            return (Criteria) this;
        }

        public Criteria andAActTitleBetween(String value1, String value2) {
            addCriterion("a_act_title between", value1, value2, "aActTitle");
            return (Criteria) this;
        }

        public Criteria andAActTitleNotBetween(String value1, String value2) {
            addCriterion("a_act_title not between", value1, value2, "aActTitle");
            return (Criteria) this;
        }

        public Criteria andAContentIsNull() {
            addCriterion("a_content is null");
            return (Criteria) this;
        }

        public Criteria andAContentIsNotNull() {
            addCriterion("a_content is not null");
            return (Criteria) this;
        }

        public Criteria andAContentEqualTo(String value) {
            addCriterion("a_content =", value, "aContent");
            return (Criteria) this;
        }

        public Criteria andAContentNotEqualTo(String value) {
            addCriterion("a_content <>", value, "aContent");
            return (Criteria) this;
        }

        public Criteria andAContentGreaterThan(String value) {
            addCriterion("a_content >", value, "aContent");
            return (Criteria) this;
        }

        public Criteria andAContentGreaterThanOrEqualTo(String value) {
            addCriterion("a_content >=", value, "aContent");
            return (Criteria) this;
        }

        public Criteria andAContentLessThan(String value) {
            addCriterion("a_content <", value, "aContent");
            return (Criteria) this;
        }

        public Criteria andAContentLessThanOrEqualTo(String value) {
            addCriterion("a_content <=", value, "aContent");
            return (Criteria) this;
        }

        public Criteria andAContentLike(String value) {
            addCriterion("a_content like", value, "aContent");
            return (Criteria) this;
        }

        public Criteria andAContentNotLike(String value) {
            addCriterion("a_content not like", value, "aContent");
            return (Criteria) this;
        }

        public Criteria andAContentIn(List<String> values) {
            addCriterion("a_content in", values, "aContent");
            return (Criteria) this;
        }

        public Criteria andAContentNotIn(List<String> values) {
            addCriterion("a_content not in", values, "aContent");
            return (Criteria) this;
        }

        public Criteria andAContentBetween(String value1, String value2) {
            addCriterion("a_content between", value1, value2, "aContent");
            return (Criteria) this;
        }

        public Criteria andAContentNotBetween(String value1, String value2) {
            addCriterion("a_content not between", value1, value2, "aContent");
            return (Criteria) this;
        }

        public Criteria andATargetIsNull() {
            addCriterion("a_target is null");
            return (Criteria) this;
        }

        public Criteria andATargetIsNotNull() {
            addCriterion("a_target is not null");
            return (Criteria) this;
        }

        public Criteria andATargetEqualTo(String value) {
            addCriterion("a_target =", value, "aTarget");
            return (Criteria) this;
        }

        public Criteria andATargetNotEqualTo(String value) {
            addCriterion("a_target <>", value, "aTarget");
            return (Criteria) this;
        }

        public Criteria andATargetGreaterThan(String value) {
            addCriterion("a_target >", value, "aTarget");
            return (Criteria) this;
        }

        public Criteria andATargetGreaterThanOrEqualTo(String value) {
            addCriterion("a_target >=", value, "aTarget");
            return (Criteria) this;
        }

        public Criteria andATargetLessThan(String value) {
            addCriterion("a_target <", value, "aTarget");
            return (Criteria) this;
        }

        public Criteria andATargetLessThanOrEqualTo(String value) {
            addCriterion("a_target <=", value, "aTarget");
            return (Criteria) this;
        }

        public Criteria andATargetLike(String value) {
            addCriterion("a_target like", value, "aTarget");
            return (Criteria) this;
        }

        public Criteria andATargetNotLike(String value) {
            addCriterion("a_target not like", value, "aTarget");
            return (Criteria) this;
        }

        public Criteria andATargetIn(List<String> values) {
            addCriterion("a_target in", values, "aTarget");
            return (Criteria) this;
        }

        public Criteria andATargetNotIn(List<String> values) {
            addCriterion("a_target not in", values, "aTarget");
            return (Criteria) this;
        }

        public Criteria andATargetBetween(String value1, String value2) {
            addCriterion("a_target between", value1, value2, "aTarget");
            return (Criteria) this;
        }

        public Criteria andATargetNotBetween(String value1, String value2) {
            addCriterion("a_target not between", value1, value2, "aTarget");
            return (Criteria) this;
        }

        public Criteria andAThumbnailIsNull() {
            addCriterion("a_thumbnail is null");
            return (Criteria) this;
        }

        public Criteria andAThumbnailIsNotNull() {
            addCriterion("a_thumbnail is not null");
            return (Criteria) this;
        }

        public Criteria andAThumbnailEqualTo(String value) {
            addCriterion("a_thumbnail =", value, "aThumbnail");
            return (Criteria) this;
        }

        public Criteria andAThumbnailNotEqualTo(String value) {
            addCriterion("a_thumbnail <>", value, "aThumbnail");
            return (Criteria) this;
        }

        public Criteria andAThumbnailGreaterThan(String value) {
            addCriterion("a_thumbnail >", value, "aThumbnail");
            return (Criteria) this;
        }

        public Criteria andAThumbnailGreaterThanOrEqualTo(String value) {
            addCriterion("a_thumbnail >=", value, "aThumbnail");
            return (Criteria) this;
        }

        public Criteria andAThumbnailLessThan(String value) {
            addCriterion("a_thumbnail <", value, "aThumbnail");
            return (Criteria) this;
        }

        public Criteria andAThumbnailLessThanOrEqualTo(String value) {
            addCriterion("a_thumbnail <=", value, "aThumbnail");
            return (Criteria) this;
        }

        public Criteria andAThumbnailLike(String value) {
            addCriterion("a_thumbnail like", value, "aThumbnail");
            return (Criteria) this;
        }

        public Criteria andAThumbnailNotLike(String value) {
            addCriterion("a_thumbnail not like", value, "aThumbnail");
            return (Criteria) this;
        }

        public Criteria andAThumbnailIn(List<String> values) {
            addCriterion("a_thumbnail in", values, "aThumbnail");
            return (Criteria) this;
        }

        public Criteria andAThumbnailNotIn(List<String> values) {
            addCriterion("a_thumbnail not in", values, "aThumbnail");
            return (Criteria) this;
        }

        public Criteria andAThumbnailBetween(String value1, String value2) {
            addCriterion("a_thumbnail between", value1, value2, "aThumbnail");
            return (Criteria) this;
        }

        public Criteria andAThumbnailNotBetween(String value1, String value2) {
            addCriterion("a_thumbnail not between", value1, value2, "aThumbnail");
            return (Criteria) this;
        }

        public Criteria andABigPhotoIsNull() {
            addCriterion("a_big_photo is null");
            return (Criteria) this;
        }

        public Criteria andABigPhotoIsNotNull() {
            addCriterion("a_big_photo is not null");
            return (Criteria) this;
        }

        public Criteria andABigPhotoEqualTo(String value) {
            addCriterion("a_big_photo =", value, "aBigPhoto");
            return (Criteria) this;
        }

        public Criteria andABigPhotoNotEqualTo(String value) {
            addCriterion("a_big_photo <>", value, "aBigPhoto");
            return (Criteria) this;
        }

        public Criteria andABigPhotoGreaterThan(String value) {
            addCriterion("a_big_photo >", value, "aBigPhoto");
            return (Criteria) this;
        }

        public Criteria andABigPhotoGreaterThanOrEqualTo(String value) {
            addCriterion("a_big_photo >=", value, "aBigPhoto");
            return (Criteria) this;
        }

        public Criteria andABigPhotoLessThan(String value) {
            addCriterion("a_big_photo <", value, "aBigPhoto");
            return (Criteria) this;
        }

        public Criteria andABigPhotoLessThanOrEqualTo(String value) {
            addCriterion("a_big_photo <=", value, "aBigPhoto");
            return (Criteria) this;
        }

        public Criteria andABigPhotoLike(String value) {
            addCriterion("a_big_photo like", value, "aBigPhoto");
            return (Criteria) this;
        }

        public Criteria andABigPhotoNotLike(String value) {
            addCriterion("a_big_photo not like", value, "aBigPhoto");
            return (Criteria) this;
        }

        public Criteria andABigPhotoIn(List<String> values) {
            addCriterion("a_big_photo in", values, "aBigPhoto");
            return (Criteria) this;
        }

        public Criteria andABigPhotoNotIn(List<String> values) {
            addCriterion("a_big_photo not in", values, "aBigPhoto");
            return (Criteria) this;
        }

        public Criteria andABigPhotoBetween(String value1, String value2) {
            addCriterion("a_big_photo between", value1, value2, "aBigPhoto");
            return (Criteria) this;
        }

        public Criteria andABigPhotoNotBetween(String value1, String value2) {
            addCriterion("a_big_photo not between", value1, value2, "aBigPhoto");
            return (Criteria) this;
        }

        public Criteria andACommentCountIsNull() {
            addCriterion("a_comment_count is null");
            return (Criteria) this;
        }

        public Criteria andACommentCountIsNotNull() {
            addCriterion("a_comment_count is not null");
            return (Criteria) this;
        }

        public Criteria andACommentCountEqualTo(Integer value) {
            addCriterion("a_comment_count =", value, "aCommentCount");
            return (Criteria) this;
        }

        public Criteria andACommentCountNotEqualTo(Integer value) {
            addCriterion("a_comment_count <>", value, "aCommentCount");
            return (Criteria) this;
        }

        public Criteria andACommentCountGreaterThan(Integer value) {
            addCriterion("a_comment_count >", value, "aCommentCount");
            return (Criteria) this;
        }

        public Criteria andACommentCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("a_comment_count >=", value, "aCommentCount");
            return (Criteria) this;
        }

        public Criteria andACommentCountLessThan(Integer value) {
            addCriterion("a_comment_count <", value, "aCommentCount");
            return (Criteria) this;
        }

        public Criteria andACommentCountLessThanOrEqualTo(Integer value) {
            addCriterion("a_comment_count <=", value, "aCommentCount");
            return (Criteria) this;
        }

        public Criteria andACommentCountIn(List<Integer> values) {
            addCriterion("a_comment_count in", values, "aCommentCount");
            return (Criteria) this;
        }

        public Criteria andACommentCountNotIn(List<Integer> values) {
            addCriterion("a_comment_count not in", values, "aCommentCount");
            return (Criteria) this;
        }

        public Criteria andACommentCountBetween(Integer value1, Integer value2) {
            addCriterion("a_comment_count between", value1, value2, "aCommentCount");
            return (Criteria) this;
        }

        public Criteria andACommentCountNotBetween(Integer value1, Integer value2) {
            addCriterion("a_comment_count not between", value1, value2, "aCommentCount");
            return (Criteria) this;
        }

        public Criteria andAApplyAmountIsNull() {
            addCriterion("a_apply_amount is null");
            return (Criteria) this;
        }

        public Criteria andAApplyAmountIsNotNull() {
            addCriterion("a_apply_amount is not null");
            return (Criteria) this;
        }

        public Criteria andAApplyAmountEqualTo(Integer value) {
            addCriterion("a_apply_amount =", value, "aApplyAmount");
            return (Criteria) this;
        }

        public Criteria andAApplyAmountNotEqualTo(Integer value) {
            addCriterion("a_apply_amount <>", value, "aApplyAmount");
            return (Criteria) this;
        }

        public Criteria andAApplyAmountGreaterThan(Integer value) {
            addCriterion("a_apply_amount >", value, "aApplyAmount");
            return (Criteria) this;
        }

        public Criteria andAApplyAmountGreaterThanOrEqualTo(Integer value) {
            addCriterion("a_apply_amount >=", value, "aApplyAmount");
            return (Criteria) this;
        }

        public Criteria andAApplyAmountLessThan(Integer value) {
            addCriterion("a_apply_amount <", value, "aApplyAmount");
            return (Criteria) this;
        }

        public Criteria andAApplyAmountLessThanOrEqualTo(Integer value) {
            addCriterion("a_apply_amount <=", value, "aApplyAmount");
            return (Criteria) this;
        }

        public Criteria andAApplyAmountIn(List<Integer> values) {
            addCriterion("a_apply_amount in", values, "aApplyAmount");
            return (Criteria) this;
        }

        public Criteria andAApplyAmountNotIn(List<Integer> values) {
            addCriterion("a_apply_amount not in", values, "aApplyAmount");
            return (Criteria) this;
        }

        public Criteria andAApplyAmountBetween(Integer value1, Integer value2) {
            addCriterion("a_apply_amount between", value1, value2, "aApplyAmount");
            return (Criteria) this;
        }

        public Criteria andAApplyAmountNotBetween(Integer value1, Integer value2) {
            addCriterion("a_apply_amount not between", value1, value2, "aApplyAmount");
            return (Criteria) this;
        }

        public Criteria andAAddressIsNull() {
            addCriterion("a_address is null");
            return (Criteria) this;
        }

        public Criteria andAAddressIsNotNull() {
            addCriterion("a_address is not null");
            return (Criteria) this;
        }

        public Criteria andAAddressEqualTo(String value) {
            addCriterion("a_address =", value, "aAddress");
            return (Criteria) this;
        }

        public Criteria andAAddressNotEqualTo(String value) {
            addCriterion("a_address <>", value, "aAddress");
            return (Criteria) this;
        }

        public Criteria andAAddressGreaterThan(String value) {
            addCriterion("a_address >", value, "aAddress");
            return (Criteria) this;
        }

        public Criteria andAAddressGreaterThanOrEqualTo(String value) {
            addCriterion("a_address >=", value, "aAddress");
            return (Criteria) this;
        }

        public Criteria andAAddressLessThan(String value) {
            addCriterion("a_address <", value, "aAddress");
            return (Criteria) this;
        }

        public Criteria andAAddressLessThanOrEqualTo(String value) {
            addCriterion("a_address <=", value, "aAddress");
            return (Criteria) this;
        }

        public Criteria andAAddressLike(String value) {
            addCriterion("a_address like", value, "aAddress");
            return (Criteria) this;
        }

        public Criteria andAAddressNotLike(String value) {
            addCriterion("a_address not like", value, "aAddress");
            return (Criteria) this;
        }

        public Criteria andAAddressIn(List<String> values) {
            addCriterion("a_address in", values, "aAddress");
            return (Criteria) this;
        }

        public Criteria andAAddressNotIn(List<String> values) {
            addCriterion("a_address not in", values, "aAddress");
            return (Criteria) this;
        }

        public Criteria andAAddressBetween(String value1, String value2) {
            addCriterion("a_address between", value1, value2, "aAddress");
            return (Criteria) this;
        }

        public Criteria andAAddressNotBetween(String value1, String value2) {
            addCriterion("a_address not between", value1, value2, "aAddress");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table a_activity
     *
     * @mbggenerated do_not_delete_during_merge Thu Jul 09 10:07:06 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table a_activity
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}