package com.info.model;

import java.util.Date;

public class Activity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_activity.a_id
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    private Integer aId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_activity.a_userid
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    private Integer aUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_activity.a_acttime
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    private Date aActtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_activity.a_act_type
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    private Integer aActType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_activity.a_act_title
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    private String aActTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_activity.a_content
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    private String aContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_activity.a_target
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    private String aTarget;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_activity.a_thumbnail
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    private String aThumbnail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_activity.a_big_photo
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    private String aBigPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_activity.a_comment_count
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    private Integer aCommentCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_activity.a_apply_amount
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    private Integer aApplyAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_activity.a_address
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    private String aAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_activity.a_id
     *
     * @return the value of a_activity.a_id
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public Integer getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_activity.a_id
     *
     * @param aId the value for a_activity.a_id
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public void setaId(Integer aId) {
        this.aId = aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_activity.a_userid
     *
     * @return the value of a_activity.a_userid
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public Integer getaUserid() {
        return aUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_activity.a_userid
     *
     * @param aUserid the value for a_activity.a_userid
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public void setaUserid(Integer aUserid) {
        this.aUserid = aUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_activity.a_acttime
     *
     * @return the value of a_activity.a_acttime
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public Date getaActtime() {
        return aActtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_activity.a_acttime
     *
     * @param aActtime the value for a_activity.a_acttime
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public void setaActtime(Date aActtime) {
        this.aActtime = aActtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_activity.a_act_type
     *
     * @return the value of a_activity.a_act_type
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public Integer getaActType() {
        return aActType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_activity.a_act_type
     *
     * @param aActType the value for a_activity.a_act_type
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public void setaActType(Integer aActType) {
        this.aActType = aActType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_activity.a_act_title
     *
     * @return the value of a_activity.a_act_title
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public String getaActTitle() {
        return aActTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_activity.a_act_title
     *
     * @param aActTitle the value for a_activity.a_act_title
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public void setaActTitle(String aActTitle) {
        this.aActTitle = aActTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_activity.a_content
     *
     * @return the value of a_activity.a_content
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public String getaContent() {
        return aContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_activity.a_content
     *
     * @param aContent the value for a_activity.a_content
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public void setaContent(String aContent) {
        this.aContent = aContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_activity.a_target
     *
     * @return the value of a_activity.a_target
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public String getaTarget() {
        return aTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_activity.a_target
     *
     * @param aTarget the value for a_activity.a_target
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public void setaTarget(String aTarget) {
        this.aTarget = aTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_activity.a_thumbnail
     *
     * @return the value of a_activity.a_thumbnail
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public String getaThumbnail() {
        return aThumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_activity.a_thumbnail
     *
     * @param aThumbnail the value for a_activity.a_thumbnail
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public void setaThumbnail(String aThumbnail) {
        this.aThumbnail = aThumbnail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_activity.a_big_photo
     *
     * @return the value of a_activity.a_big_photo
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public String getaBigPhoto() {
        return aBigPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_activity.a_big_photo
     *
     * @param aBigPhoto the value for a_activity.a_big_photo
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public void setaBigPhoto(String aBigPhoto) {
        this.aBigPhoto = aBigPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_activity.a_comment_count
     *
     * @return the value of a_activity.a_comment_count
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public Integer getaCommentCount() {
        return aCommentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_activity.a_comment_count
     *
     * @param aCommentCount the value for a_activity.a_comment_count
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public void setaCommentCount(Integer aCommentCount) {
        this.aCommentCount = aCommentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_activity.a_apply_amount
     *
     * @return the value of a_activity.a_apply_amount
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public Integer getaApplyAmount() {
        return aApplyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_activity.a_apply_amount
     *
     * @param aApplyAmount the value for a_activity.a_apply_amount
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public void setaApplyAmount(Integer aApplyAmount) {
        this.aApplyAmount = aApplyAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_activity.a_address
     *
     * @return the value of a_activity.a_address
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public String getaAddress() {
        return aAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_activity.a_address
     *
     * @param aAddress the value for a_activity.a_address
     *
     * @mbggenerated Thu Jul 09 10:07:06 CST 2015
     */
    public void setaAddress(String aAddress) {
        this.aAddress = aAddress;
    }
}