package com.info.model;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column u_user.u_id
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	private Integer uId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column u_user.u_nickname
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	private String uNickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column u_user.u_gender
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	private String uGender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column u_user.u_password
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	private String uPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column u_user.u_tel
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	private String uTel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column u_user.u_email
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	private String uEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column u_user.u_birthday
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	private Date uBirthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column u_user.u_age
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	private Short uAge;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column u_user.u_large_avatar
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	private String uLargeAvatar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column u_user.u_small_avatar
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	private String uSmallAvatar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column u_user.u_identity
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	private String uIdentity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column u_user.u_love_state
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	private String uLoveState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column u_user.u_provinceid
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	private Integer uProvinceid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column u_user.u_cityid
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	private Integer uCityid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column u_user.u_schoolid
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	private Integer uSchoolid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column u_user.u_interest_ids
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	private String uInterestIds;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column u_user.u_skill_ids
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	private String uSkillIds;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column u_user.u_industry_id
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	private Integer uIndustryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column u_user.u_introduce
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	private String uIntroduce;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column u_user.u_post_amount
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	private Integer uPostAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column u_user.u_act_amount
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	private Integer uActAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column u_user.u_student_number
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	private String uStudentNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column u_user.u_student_pass
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	private String uStudentPass;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column u_user.u_id
	 * @return  the value of u_user.u_id
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public Integer getuId() {
		return uId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column u_user.u_id
	 * @param uId  the value for u_user.u_id
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public void setuId(Integer uId) {
		this.uId = uId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column u_user.u_nickname
	 * @return  the value of u_user.u_nickname
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public String getuNickname() {
		return uNickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column u_user.u_nickname
	 * @param uNickname  the value for u_user.u_nickname
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public void setuNickname(String uNickname) {
		this.uNickname = uNickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column u_user.u_gender
	 * @return  the value of u_user.u_gender
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public String getuGender() {
		return uGender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column u_user.u_gender
	 * @param uGender  the value for u_user.u_gender
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public void setuGender(String uGender) {
		this.uGender = uGender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column u_user.u_password
	 * @return  the value of u_user.u_password
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public String getuPassword() {
		return uPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column u_user.u_password
	 * @param uPassword  the value for u_user.u_password
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public void setuPassword(String uPassword) {
		this.uPassword = uPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column u_user.u_tel
	 * @return  the value of u_user.u_tel
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public String getuTel() {
		return uTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column u_user.u_tel
	 * @param uTel  the value for u_user.u_tel
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public void setuTel(String uTel) {
		this.uTel = uTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column u_user.u_email
	 * @return  the value of u_user.u_email
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public String getuEmail() {
		return uEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column u_user.u_email
	 * @param uEmail  the value for u_user.u_email
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public void setuEmail(String uEmail) {
		this.uEmail = uEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column u_user.u_birthday
	 * @return  the value of u_user.u_birthday
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public Date getuBirthday() {
		return uBirthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column u_user.u_birthday
	 * @param uBirthday  the value for u_user.u_birthday
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public void setuBirthday(Date uBirthday) {
		this.uBirthday = uBirthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column u_user.u_age
	 * @return  the value of u_user.u_age
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public Short getuAge() {
		return uAge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column u_user.u_age
	 * @param uAge  the value for u_user.u_age
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public void setuAge(Short uAge) {
		this.uAge = uAge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column u_user.u_large_avatar
	 * @return  the value of u_user.u_large_avatar
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public String getuLargeAvatar() {
		return uLargeAvatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column u_user.u_large_avatar
	 * @param uLargeAvatar  the value for u_user.u_large_avatar
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public void setuLargeAvatar(String uLargeAvatar) {
		this.uLargeAvatar = uLargeAvatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column u_user.u_small_avatar
	 * @return  the value of u_user.u_small_avatar
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public String getuSmallAvatar() {
		return uSmallAvatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column u_user.u_small_avatar
	 * @param uSmallAvatar  the value for u_user.u_small_avatar
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public void setuSmallAvatar(String uSmallAvatar) {
		this.uSmallAvatar = uSmallAvatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column u_user.u_identity
	 * @return  the value of u_user.u_identity
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public String getuIdentity() {
		return uIdentity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column u_user.u_identity
	 * @param uIdentity  the value for u_user.u_identity
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public void setuIdentity(String uIdentity) {
		this.uIdentity = uIdentity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column u_user.u_love_state
	 * @return  the value of u_user.u_love_state
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public String getuLoveState() {
		return uLoveState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column u_user.u_love_state
	 * @param uLoveState  the value for u_user.u_love_state
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public void setuLoveState(String uLoveState) {
		this.uLoveState = uLoveState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column u_user.u_provinceid
	 * @return  the value of u_user.u_provinceid
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public Integer getuProvinceid() {
		return uProvinceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column u_user.u_provinceid
	 * @param uProvinceid  the value for u_user.u_provinceid
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public void setuProvinceid(Integer uProvinceid) {
		this.uProvinceid = uProvinceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column u_user.u_cityid
	 * @return  the value of u_user.u_cityid
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public Integer getuCityid() {
		return uCityid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column u_user.u_cityid
	 * @param uCityid  the value for u_user.u_cityid
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public void setuCityid(Integer uCityid) {
		this.uCityid = uCityid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column u_user.u_schoolid
	 * @return  the value of u_user.u_schoolid
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public Integer getuSchoolid() {
		return uSchoolid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column u_user.u_schoolid
	 * @param uSchoolid  the value for u_user.u_schoolid
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public void setuSchoolid(Integer uSchoolid) {
		this.uSchoolid = uSchoolid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column u_user.u_interest_ids
	 * @return  the value of u_user.u_interest_ids
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public String getuInterestIds() {
		return uInterestIds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column u_user.u_interest_ids
	 * @param uInterestIds  the value for u_user.u_interest_ids
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public void setuInterestIds(String uInterestIds) {
		this.uInterestIds = uInterestIds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column u_user.u_skill_ids
	 * @return  the value of u_user.u_skill_ids
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public String getuSkillIds() {
		return uSkillIds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column u_user.u_skill_ids
	 * @param uSkillIds  the value for u_user.u_skill_ids
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public void setuSkillIds(String uSkillIds) {
		this.uSkillIds = uSkillIds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column u_user.u_industry_id
	 * @return  the value of u_user.u_industry_id
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public Integer getuIndustryId() {
		return uIndustryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column u_user.u_industry_id
	 * @param uIndustryId  the value for u_user.u_industry_id
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public void setuIndustryId(Integer uIndustryId) {
		this.uIndustryId = uIndustryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column u_user.u_introduce
	 * @return  the value of u_user.u_introduce
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public String getuIntroduce() {
		return uIntroduce;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column u_user.u_introduce
	 * @param uIntroduce  the value for u_user.u_introduce
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public void setuIntroduce(String uIntroduce) {
		this.uIntroduce = uIntroduce;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column u_user.u_post_amount
	 * @return  the value of u_user.u_post_amount
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public Integer getuPostAmount() {
		return uPostAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column u_user.u_post_amount
	 * @param uPostAmount  the value for u_user.u_post_amount
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public void setuPostAmount(Integer uPostAmount) {
		this.uPostAmount = uPostAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column u_user.u_act_amount
	 * @return  the value of u_user.u_act_amount
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public Integer getuActAmount() {
		return uActAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column u_user.u_act_amount
	 * @param uActAmount  the value for u_user.u_act_amount
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public void setuActAmount(Integer uActAmount) {
		this.uActAmount = uActAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column u_user.u_student_number
	 * @return  the value of u_user.u_student_number
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public String getuStudentNumber() {
		return uStudentNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column u_user.u_student_number
	 * @param uStudentNumber  the value for u_user.u_student_number
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public void setuStudentNumber(String uStudentNumber) {
		this.uStudentNumber = uStudentNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column u_user.u_student_pass
	 * @return  the value of u_user.u_student_pass
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public String getuStudentPass() {
		return uStudentPass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column u_user.u_student_pass
	 * @param uStudentPass  the value for u_user.u_student_pass
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public void setuStudentPass(String uStudentPass) {
		this.uStudentPass = uStudentPass;
	}
}