package com.info.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class UserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table u_user
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table u_user
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table u_user
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table u_user
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public UserExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table u_user
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table u_user
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table u_user
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table u_user
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table u_user
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table u_user
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table u_user
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table u_user
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table u_user
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table u_user
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table u_user
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andUIdIsNull() {
			addCriterion("u_id is null");
			return (Criteria) this;
		}

		public Criteria andUIdIsNotNull() {
			addCriterion("u_id is not null");
			return (Criteria) this;
		}

		public Criteria andUIdEqualTo(Integer value) {
			addCriterion("u_id =", value, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdNotEqualTo(Integer value) {
			addCriterion("u_id <>", value, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdGreaterThan(Integer value) {
			addCriterion("u_id >", value, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("u_id >=", value, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdLessThan(Integer value) {
			addCriterion("u_id <", value, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdLessThanOrEqualTo(Integer value) {
			addCriterion("u_id <=", value, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdIn(List<Integer> values) {
			addCriterion("u_id in", values, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdNotIn(List<Integer> values) {
			addCriterion("u_id not in", values, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdBetween(Integer value1, Integer value2) {
			addCriterion("u_id between", value1, value2, "uId");
			return (Criteria) this;
		}

		public Criteria andUIdNotBetween(Integer value1, Integer value2) {
			addCriterion("u_id not between", value1, value2, "uId");
			return (Criteria) this;
		}

		public Criteria andUNicknameIsNull() {
			addCriterion("u_nickname is null");
			return (Criteria) this;
		}

		public Criteria andUNicknameIsNotNull() {
			addCriterion("u_nickname is not null");
			return (Criteria) this;
		}

		public Criteria andUNicknameEqualTo(String value) {
			addCriterion("u_nickname =", value, "uNickname");
			return (Criteria) this;
		}

		public Criteria andUNicknameNotEqualTo(String value) {
			addCriterion("u_nickname <>", value, "uNickname");
			return (Criteria) this;
		}

		public Criteria andUNicknameGreaterThan(String value) {
			addCriterion("u_nickname >", value, "uNickname");
			return (Criteria) this;
		}

		public Criteria andUNicknameGreaterThanOrEqualTo(String value) {
			addCriterion("u_nickname >=", value, "uNickname");
			return (Criteria) this;
		}

		public Criteria andUNicknameLessThan(String value) {
			addCriterion("u_nickname <", value, "uNickname");
			return (Criteria) this;
		}

		public Criteria andUNicknameLessThanOrEqualTo(String value) {
			addCriterion("u_nickname <=", value, "uNickname");
			return (Criteria) this;
		}

		public Criteria andUNicknameLike(String value) {
			addCriterion("u_nickname like", value, "uNickname");
			return (Criteria) this;
		}

		public Criteria andUNicknameNotLike(String value) {
			addCriterion("u_nickname not like", value, "uNickname");
			return (Criteria) this;
		}

		public Criteria andUNicknameIn(List<String> values) {
			addCriterion("u_nickname in", values, "uNickname");
			return (Criteria) this;
		}

		public Criteria andUNicknameNotIn(List<String> values) {
			addCriterion("u_nickname not in", values, "uNickname");
			return (Criteria) this;
		}

		public Criteria andUNicknameBetween(String value1, String value2) {
			addCriterion("u_nickname between", value1, value2, "uNickname");
			return (Criteria) this;
		}

		public Criteria andUNicknameNotBetween(String value1, String value2) {
			addCriterion("u_nickname not between", value1, value2, "uNickname");
			return (Criteria) this;
		}

		public Criteria andUGenderIsNull() {
			addCriterion("u_gender is null");
			return (Criteria) this;
		}

		public Criteria andUGenderIsNotNull() {
			addCriterion("u_gender is not null");
			return (Criteria) this;
		}

		public Criteria andUGenderEqualTo(String value) {
			addCriterion("u_gender =", value, "uGender");
			return (Criteria) this;
		}

		public Criteria andUGenderNotEqualTo(String value) {
			addCriterion("u_gender <>", value, "uGender");
			return (Criteria) this;
		}

		public Criteria andUGenderGreaterThan(String value) {
			addCriterion("u_gender >", value, "uGender");
			return (Criteria) this;
		}

		public Criteria andUGenderGreaterThanOrEqualTo(String value) {
			addCriterion("u_gender >=", value, "uGender");
			return (Criteria) this;
		}

		public Criteria andUGenderLessThan(String value) {
			addCriterion("u_gender <", value, "uGender");
			return (Criteria) this;
		}

		public Criteria andUGenderLessThanOrEqualTo(String value) {
			addCriterion("u_gender <=", value, "uGender");
			return (Criteria) this;
		}

		public Criteria andUGenderLike(String value) {
			addCriterion("u_gender like", value, "uGender");
			return (Criteria) this;
		}

		public Criteria andUGenderNotLike(String value) {
			addCriterion("u_gender not like", value, "uGender");
			return (Criteria) this;
		}

		public Criteria andUGenderIn(List<String> values) {
			addCriterion("u_gender in", values, "uGender");
			return (Criteria) this;
		}

		public Criteria andUGenderNotIn(List<String> values) {
			addCriterion("u_gender not in", values, "uGender");
			return (Criteria) this;
		}

		public Criteria andUGenderBetween(String value1, String value2) {
			addCriterion("u_gender between", value1, value2, "uGender");
			return (Criteria) this;
		}

		public Criteria andUGenderNotBetween(String value1, String value2) {
			addCriterion("u_gender not between", value1, value2, "uGender");
			return (Criteria) this;
		}

		public Criteria andUPasswordIsNull() {
			addCriterion("u_password is null");
			return (Criteria) this;
		}

		public Criteria andUPasswordIsNotNull() {
			addCriterion("u_password is not null");
			return (Criteria) this;
		}

		public Criteria andUPasswordEqualTo(String value) {
			addCriterion("u_password =", value, "uPassword");
			return (Criteria) this;
		}

		public Criteria andUPasswordNotEqualTo(String value) {
			addCriterion("u_password <>", value, "uPassword");
			return (Criteria) this;
		}

		public Criteria andUPasswordGreaterThan(String value) {
			addCriterion("u_password >", value, "uPassword");
			return (Criteria) this;
		}

		public Criteria andUPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("u_password >=", value, "uPassword");
			return (Criteria) this;
		}

		public Criteria andUPasswordLessThan(String value) {
			addCriterion("u_password <", value, "uPassword");
			return (Criteria) this;
		}

		public Criteria andUPasswordLessThanOrEqualTo(String value) {
			addCriterion("u_password <=", value, "uPassword");
			return (Criteria) this;
		}

		public Criteria andUPasswordLike(String value) {
			addCriterion("u_password like", value, "uPassword");
			return (Criteria) this;
		}

		public Criteria andUPasswordNotLike(String value) {
			addCriterion("u_password not like", value, "uPassword");
			return (Criteria) this;
		}

		public Criteria andUPasswordIn(List<String> values) {
			addCriterion("u_password in", values, "uPassword");
			return (Criteria) this;
		}

		public Criteria andUPasswordNotIn(List<String> values) {
			addCriterion("u_password not in", values, "uPassword");
			return (Criteria) this;
		}

		public Criteria andUPasswordBetween(String value1, String value2) {
			addCriterion("u_password between", value1, value2, "uPassword");
			return (Criteria) this;
		}

		public Criteria andUPasswordNotBetween(String value1, String value2) {
			addCriterion("u_password not between", value1, value2, "uPassword");
			return (Criteria) this;
		}

		public Criteria andUTelIsNull() {
			addCriterion("u_tel is null");
			return (Criteria) this;
		}

		public Criteria andUTelIsNotNull() {
			addCriterion("u_tel is not null");
			return (Criteria) this;
		}

		public Criteria andUTelEqualTo(String value) {
			addCriterion("u_tel =", value, "uTel");
			return (Criteria) this;
		}

		public Criteria andUTelNotEqualTo(String value) {
			addCriterion("u_tel <>", value, "uTel");
			return (Criteria) this;
		}

		public Criteria andUTelGreaterThan(String value) {
			addCriterion("u_tel >", value, "uTel");
			return (Criteria) this;
		}

		public Criteria andUTelGreaterThanOrEqualTo(String value) {
			addCriterion("u_tel >=", value, "uTel");
			return (Criteria) this;
		}

		public Criteria andUTelLessThan(String value) {
			addCriterion("u_tel <", value, "uTel");
			return (Criteria) this;
		}

		public Criteria andUTelLessThanOrEqualTo(String value) {
			addCriterion("u_tel <=", value, "uTel");
			return (Criteria) this;
		}

		public Criteria andUTelLike(String value) {
			addCriterion("u_tel like", value, "uTel");
			return (Criteria) this;
		}

		public Criteria andUTelNotLike(String value) {
			addCriterion("u_tel not like", value, "uTel");
			return (Criteria) this;
		}

		public Criteria andUTelIn(List<String> values) {
			addCriterion("u_tel in", values, "uTel");
			return (Criteria) this;
		}

		public Criteria andUTelNotIn(List<String> values) {
			addCriterion("u_tel not in", values, "uTel");
			return (Criteria) this;
		}

		public Criteria andUTelBetween(String value1, String value2) {
			addCriterion("u_tel between", value1, value2, "uTel");
			return (Criteria) this;
		}

		public Criteria andUTelNotBetween(String value1, String value2) {
			addCriterion("u_tel not between", value1, value2, "uTel");
			return (Criteria) this;
		}

		public Criteria andUEmailIsNull() {
			addCriterion("u_email is null");
			return (Criteria) this;
		}

		public Criteria andUEmailIsNotNull() {
			addCriterion("u_email is not null");
			return (Criteria) this;
		}

		public Criteria andUEmailEqualTo(String value) {
			addCriterion("u_email =", value, "uEmail");
			return (Criteria) this;
		}

		public Criteria andUEmailNotEqualTo(String value) {
			addCriterion("u_email <>", value, "uEmail");
			return (Criteria) this;
		}

		public Criteria andUEmailGreaterThan(String value) {
			addCriterion("u_email >", value, "uEmail");
			return (Criteria) this;
		}

		public Criteria andUEmailGreaterThanOrEqualTo(String value) {
			addCriterion("u_email >=", value, "uEmail");
			return (Criteria) this;
		}

		public Criteria andUEmailLessThan(String value) {
			addCriterion("u_email <", value, "uEmail");
			return (Criteria) this;
		}

		public Criteria andUEmailLessThanOrEqualTo(String value) {
			addCriterion("u_email <=", value, "uEmail");
			return (Criteria) this;
		}

		public Criteria andUEmailLike(String value) {
			addCriterion("u_email like", value, "uEmail");
			return (Criteria) this;
		}

		public Criteria andUEmailNotLike(String value) {
			addCriterion("u_email not like", value, "uEmail");
			return (Criteria) this;
		}

		public Criteria andUEmailIn(List<String> values) {
			addCriterion("u_email in", values, "uEmail");
			return (Criteria) this;
		}

		public Criteria andUEmailNotIn(List<String> values) {
			addCriterion("u_email not in", values, "uEmail");
			return (Criteria) this;
		}

		public Criteria andUEmailBetween(String value1, String value2) {
			addCriterion("u_email between", value1, value2, "uEmail");
			return (Criteria) this;
		}

		public Criteria andUEmailNotBetween(String value1, String value2) {
			addCriterion("u_email not between", value1, value2, "uEmail");
			return (Criteria) this;
		}

		public Criteria andUBirthdayIsNull() {
			addCriterion("u_birthday is null");
			return (Criteria) this;
		}

		public Criteria andUBirthdayIsNotNull() {
			addCriterion("u_birthday is not null");
			return (Criteria) this;
		}

		public Criteria andUBirthdayEqualTo(Date value) {
			addCriterionForJDBCDate("u_birthday =", value, "uBirthday");
			return (Criteria) this;
		}

		public Criteria andUBirthdayNotEqualTo(Date value) {
			addCriterionForJDBCDate("u_birthday <>", value, "uBirthday");
			return (Criteria) this;
		}

		public Criteria andUBirthdayGreaterThan(Date value) {
			addCriterionForJDBCDate("u_birthday >", value, "uBirthday");
			return (Criteria) this;
		}

		public Criteria andUBirthdayGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("u_birthday >=", value, "uBirthday");
			return (Criteria) this;
		}

		public Criteria andUBirthdayLessThan(Date value) {
			addCriterionForJDBCDate("u_birthday <", value, "uBirthday");
			return (Criteria) this;
		}

		public Criteria andUBirthdayLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("u_birthday <=", value, "uBirthday");
			return (Criteria) this;
		}

		public Criteria andUBirthdayIn(List<Date> values) {
			addCriterionForJDBCDate("u_birthday in", values, "uBirthday");
			return (Criteria) this;
		}

		public Criteria andUBirthdayNotIn(List<Date> values) {
			addCriterionForJDBCDate("u_birthday not in", values, "uBirthday");
			return (Criteria) this;
		}

		public Criteria andUBirthdayBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("u_birthday between", value1, value2,
					"uBirthday");
			return (Criteria) this;
		}

		public Criteria andUBirthdayNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("u_birthday not between", value1, value2,
					"uBirthday");
			return (Criteria) this;
		}

		public Criteria andUAgeIsNull() {
			addCriterion("u_age is null");
			return (Criteria) this;
		}

		public Criteria andUAgeIsNotNull() {
			addCriterion("u_age is not null");
			return (Criteria) this;
		}

		public Criteria andUAgeEqualTo(Short value) {
			addCriterion("u_age =", value, "uAge");
			return (Criteria) this;
		}

		public Criteria andUAgeNotEqualTo(Short value) {
			addCriterion("u_age <>", value, "uAge");
			return (Criteria) this;
		}

		public Criteria andUAgeGreaterThan(Short value) {
			addCriterion("u_age >", value, "uAge");
			return (Criteria) this;
		}

		public Criteria andUAgeGreaterThanOrEqualTo(Short value) {
			addCriterion("u_age >=", value, "uAge");
			return (Criteria) this;
		}

		public Criteria andUAgeLessThan(Short value) {
			addCriterion("u_age <", value, "uAge");
			return (Criteria) this;
		}

		public Criteria andUAgeLessThanOrEqualTo(Short value) {
			addCriterion("u_age <=", value, "uAge");
			return (Criteria) this;
		}

		public Criteria andUAgeIn(List<Short> values) {
			addCriterion("u_age in", values, "uAge");
			return (Criteria) this;
		}

		public Criteria andUAgeNotIn(List<Short> values) {
			addCriterion("u_age not in", values, "uAge");
			return (Criteria) this;
		}

		public Criteria andUAgeBetween(Short value1, Short value2) {
			addCriterion("u_age between", value1, value2, "uAge");
			return (Criteria) this;
		}

		public Criteria andUAgeNotBetween(Short value1, Short value2) {
			addCriterion("u_age not between", value1, value2, "uAge");
			return (Criteria) this;
		}

		public Criteria andULargeAvatarIsNull() {
			addCriterion("u_large_avatar is null");
			return (Criteria) this;
		}

		public Criteria andULargeAvatarIsNotNull() {
			addCriterion("u_large_avatar is not null");
			return (Criteria) this;
		}

		public Criteria andULargeAvatarEqualTo(String value) {
			addCriterion("u_large_avatar =", value, "uLargeAvatar");
			return (Criteria) this;
		}

		public Criteria andULargeAvatarNotEqualTo(String value) {
			addCriterion("u_large_avatar <>", value, "uLargeAvatar");
			return (Criteria) this;
		}

		public Criteria andULargeAvatarGreaterThan(String value) {
			addCriterion("u_large_avatar >", value, "uLargeAvatar");
			return (Criteria) this;
		}

		public Criteria andULargeAvatarGreaterThanOrEqualTo(String value) {
			addCriterion("u_large_avatar >=", value, "uLargeAvatar");
			return (Criteria) this;
		}

		public Criteria andULargeAvatarLessThan(String value) {
			addCriterion("u_large_avatar <", value, "uLargeAvatar");
			return (Criteria) this;
		}

		public Criteria andULargeAvatarLessThanOrEqualTo(String value) {
			addCriterion("u_large_avatar <=", value, "uLargeAvatar");
			return (Criteria) this;
		}

		public Criteria andULargeAvatarLike(String value) {
			addCriterion("u_large_avatar like", value, "uLargeAvatar");
			return (Criteria) this;
		}

		public Criteria andULargeAvatarNotLike(String value) {
			addCriterion("u_large_avatar not like", value, "uLargeAvatar");
			return (Criteria) this;
		}

		public Criteria andULargeAvatarIn(List<String> values) {
			addCriterion("u_large_avatar in", values, "uLargeAvatar");
			return (Criteria) this;
		}

		public Criteria andULargeAvatarNotIn(List<String> values) {
			addCriterion("u_large_avatar not in", values, "uLargeAvatar");
			return (Criteria) this;
		}

		public Criteria andULargeAvatarBetween(String value1, String value2) {
			addCriterion("u_large_avatar between", value1, value2,
					"uLargeAvatar");
			return (Criteria) this;
		}

		public Criteria andULargeAvatarNotBetween(String value1, String value2) {
			addCriterion("u_large_avatar not between", value1, value2,
					"uLargeAvatar");
			return (Criteria) this;
		}

		public Criteria andUSmallAvatarIsNull() {
			addCriterion("u_small_avatar is null");
			return (Criteria) this;
		}

		public Criteria andUSmallAvatarIsNotNull() {
			addCriterion("u_small_avatar is not null");
			return (Criteria) this;
		}

		public Criteria andUSmallAvatarEqualTo(String value) {
			addCriterion("u_small_avatar =", value, "uSmallAvatar");
			return (Criteria) this;
		}

		public Criteria andUSmallAvatarNotEqualTo(String value) {
			addCriterion("u_small_avatar <>", value, "uSmallAvatar");
			return (Criteria) this;
		}

		public Criteria andUSmallAvatarGreaterThan(String value) {
			addCriterion("u_small_avatar >", value, "uSmallAvatar");
			return (Criteria) this;
		}

		public Criteria andUSmallAvatarGreaterThanOrEqualTo(String value) {
			addCriterion("u_small_avatar >=", value, "uSmallAvatar");
			return (Criteria) this;
		}

		public Criteria andUSmallAvatarLessThan(String value) {
			addCriterion("u_small_avatar <", value, "uSmallAvatar");
			return (Criteria) this;
		}

		public Criteria andUSmallAvatarLessThanOrEqualTo(String value) {
			addCriterion("u_small_avatar <=", value, "uSmallAvatar");
			return (Criteria) this;
		}

		public Criteria andUSmallAvatarLike(String value) {
			addCriterion("u_small_avatar like", value, "uSmallAvatar");
			return (Criteria) this;
		}

		public Criteria andUSmallAvatarNotLike(String value) {
			addCriterion("u_small_avatar not like", value, "uSmallAvatar");
			return (Criteria) this;
		}

		public Criteria andUSmallAvatarIn(List<String> values) {
			addCriterion("u_small_avatar in", values, "uSmallAvatar");
			return (Criteria) this;
		}

		public Criteria andUSmallAvatarNotIn(List<String> values) {
			addCriterion("u_small_avatar not in", values, "uSmallAvatar");
			return (Criteria) this;
		}

		public Criteria andUSmallAvatarBetween(String value1, String value2) {
			addCriterion("u_small_avatar between", value1, value2,
					"uSmallAvatar");
			return (Criteria) this;
		}

		public Criteria andUSmallAvatarNotBetween(String value1, String value2) {
			addCriterion("u_small_avatar not between", value1, value2,
					"uSmallAvatar");
			return (Criteria) this;
		}

		public Criteria andUIdentityIsNull() {
			addCriterion("u_identity is null");
			return (Criteria) this;
		}

		public Criteria andUIdentityIsNotNull() {
			addCriterion("u_identity is not null");
			return (Criteria) this;
		}

		public Criteria andUIdentityEqualTo(String value) {
			addCriterion("u_identity =", value, "uIdentity");
			return (Criteria) this;
		}

		public Criteria andUIdentityNotEqualTo(String value) {
			addCriterion("u_identity <>", value, "uIdentity");
			return (Criteria) this;
		}

		public Criteria andUIdentityGreaterThan(String value) {
			addCriterion("u_identity >", value, "uIdentity");
			return (Criteria) this;
		}

		public Criteria andUIdentityGreaterThanOrEqualTo(String value) {
			addCriterion("u_identity >=", value, "uIdentity");
			return (Criteria) this;
		}

		public Criteria andUIdentityLessThan(String value) {
			addCriterion("u_identity <", value, "uIdentity");
			return (Criteria) this;
		}

		public Criteria andUIdentityLessThanOrEqualTo(String value) {
			addCriterion("u_identity <=", value, "uIdentity");
			return (Criteria) this;
		}

		public Criteria andUIdentityLike(String value) {
			addCriterion("u_identity like", value, "uIdentity");
			return (Criteria) this;
		}

		public Criteria andUIdentityNotLike(String value) {
			addCriterion("u_identity not like", value, "uIdentity");
			return (Criteria) this;
		}

		public Criteria andUIdentityIn(List<String> values) {
			addCriterion("u_identity in", values, "uIdentity");
			return (Criteria) this;
		}

		public Criteria andUIdentityNotIn(List<String> values) {
			addCriterion("u_identity not in", values, "uIdentity");
			return (Criteria) this;
		}

		public Criteria andUIdentityBetween(String value1, String value2) {
			addCriterion("u_identity between", value1, value2, "uIdentity");
			return (Criteria) this;
		}

		public Criteria andUIdentityNotBetween(String value1, String value2) {
			addCriterion("u_identity not between", value1, value2, "uIdentity");
			return (Criteria) this;
		}

		public Criteria andULoveStateIsNull() {
			addCriterion("u_love_state is null");
			return (Criteria) this;
		}

		public Criteria andULoveStateIsNotNull() {
			addCriterion("u_love_state is not null");
			return (Criteria) this;
		}

		public Criteria andULoveStateEqualTo(String value) {
			addCriterion("u_love_state =", value, "uLoveState");
			return (Criteria) this;
		}

		public Criteria andULoveStateNotEqualTo(String value) {
			addCriterion("u_love_state <>", value, "uLoveState");
			return (Criteria) this;
		}

		public Criteria andULoveStateGreaterThan(String value) {
			addCriterion("u_love_state >", value, "uLoveState");
			return (Criteria) this;
		}

		public Criteria andULoveStateGreaterThanOrEqualTo(String value) {
			addCriterion("u_love_state >=", value, "uLoveState");
			return (Criteria) this;
		}

		public Criteria andULoveStateLessThan(String value) {
			addCriterion("u_love_state <", value, "uLoveState");
			return (Criteria) this;
		}

		public Criteria andULoveStateLessThanOrEqualTo(String value) {
			addCriterion("u_love_state <=", value, "uLoveState");
			return (Criteria) this;
		}

		public Criteria andULoveStateLike(String value) {
			addCriterion("u_love_state like", value, "uLoveState");
			return (Criteria) this;
		}

		public Criteria andULoveStateNotLike(String value) {
			addCriterion("u_love_state not like", value, "uLoveState");
			return (Criteria) this;
		}

		public Criteria andULoveStateIn(List<String> values) {
			addCriterion("u_love_state in", values, "uLoveState");
			return (Criteria) this;
		}

		public Criteria andULoveStateNotIn(List<String> values) {
			addCriterion("u_love_state not in", values, "uLoveState");
			return (Criteria) this;
		}

		public Criteria andULoveStateBetween(String value1, String value2) {
			addCriterion("u_love_state between", value1, value2, "uLoveState");
			return (Criteria) this;
		}

		public Criteria andULoveStateNotBetween(String value1, String value2) {
			addCriterion("u_love_state not between", value1, value2,
					"uLoveState");
			return (Criteria) this;
		}

		public Criteria andUProvinceidIsNull() {
			addCriterion("u_provinceid is null");
			return (Criteria) this;
		}

		public Criteria andUProvinceidIsNotNull() {
			addCriterion("u_provinceid is not null");
			return (Criteria) this;
		}

		public Criteria andUProvinceidEqualTo(Integer value) {
			addCriterion("u_provinceid =", value, "uProvinceid");
			return (Criteria) this;
		}

		public Criteria andUProvinceidNotEqualTo(Integer value) {
			addCriterion("u_provinceid <>", value, "uProvinceid");
			return (Criteria) this;
		}

		public Criteria andUProvinceidGreaterThan(Integer value) {
			addCriterion("u_provinceid >", value, "uProvinceid");
			return (Criteria) this;
		}

		public Criteria andUProvinceidGreaterThanOrEqualTo(Integer value) {
			addCriterion("u_provinceid >=", value, "uProvinceid");
			return (Criteria) this;
		}

		public Criteria andUProvinceidLessThan(Integer value) {
			addCriterion("u_provinceid <", value, "uProvinceid");
			return (Criteria) this;
		}

		public Criteria andUProvinceidLessThanOrEqualTo(Integer value) {
			addCriterion("u_provinceid <=", value, "uProvinceid");
			return (Criteria) this;
		}

		public Criteria andUProvinceidIn(List<Integer> values) {
			addCriterion("u_provinceid in", values, "uProvinceid");
			return (Criteria) this;
		}

		public Criteria andUProvinceidNotIn(List<Integer> values) {
			addCriterion("u_provinceid not in", values, "uProvinceid");
			return (Criteria) this;
		}

		public Criteria andUProvinceidBetween(Integer value1, Integer value2) {
			addCriterion("u_provinceid between", value1, value2, "uProvinceid");
			return (Criteria) this;
		}

		public Criteria andUProvinceidNotBetween(Integer value1, Integer value2) {
			addCriterion("u_provinceid not between", value1, value2,
					"uProvinceid");
			return (Criteria) this;
		}

		public Criteria andUCityidIsNull() {
			addCriterion("u_cityid is null");
			return (Criteria) this;
		}

		public Criteria andUCityidIsNotNull() {
			addCriterion("u_cityid is not null");
			return (Criteria) this;
		}

		public Criteria andUCityidEqualTo(Integer value) {
			addCriterion("u_cityid =", value, "uCityid");
			return (Criteria) this;
		}

		public Criteria andUCityidNotEqualTo(Integer value) {
			addCriterion("u_cityid <>", value, "uCityid");
			return (Criteria) this;
		}

		public Criteria andUCityidGreaterThan(Integer value) {
			addCriterion("u_cityid >", value, "uCityid");
			return (Criteria) this;
		}

		public Criteria andUCityidGreaterThanOrEqualTo(Integer value) {
			addCriterion("u_cityid >=", value, "uCityid");
			return (Criteria) this;
		}

		public Criteria andUCityidLessThan(Integer value) {
			addCriterion("u_cityid <", value, "uCityid");
			return (Criteria) this;
		}

		public Criteria andUCityidLessThanOrEqualTo(Integer value) {
			addCriterion("u_cityid <=", value, "uCityid");
			return (Criteria) this;
		}

		public Criteria andUCityidIn(List<Integer> values) {
			addCriterion("u_cityid in", values, "uCityid");
			return (Criteria) this;
		}

		public Criteria andUCityidNotIn(List<Integer> values) {
			addCriterion("u_cityid not in", values, "uCityid");
			return (Criteria) this;
		}

		public Criteria andUCityidBetween(Integer value1, Integer value2) {
			addCriterion("u_cityid between", value1, value2, "uCityid");
			return (Criteria) this;
		}

		public Criteria andUCityidNotBetween(Integer value1, Integer value2) {
			addCriterion("u_cityid not between", value1, value2, "uCityid");
			return (Criteria) this;
		}

		public Criteria andUSchoolidIsNull() {
			addCriterion("u_schoolid is null");
			return (Criteria) this;
		}

		public Criteria andUSchoolidIsNotNull() {
			addCriterion("u_schoolid is not null");
			return (Criteria) this;
		}

		public Criteria andUSchoolidEqualTo(Integer value) {
			addCriterion("u_schoolid =", value, "uSchoolid");
			return (Criteria) this;
		}

		public Criteria andUSchoolidNotEqualTo(Integer value) {
			addCriterion("u_schoolid <>", value, "uSchoolid");
			return (Criteria) this;
		}

		public Criteria andUSchoolidGreaterThan(Integer value) {
			addCriterion("u_schoolid >", value, "uSchoolid");
			return (Criteria) this;
		}

		public Criteria andUSchoolidGreaterThanOrEqualTo(Integer value) {
			addCriterion("u_schoolid >=", value, "uSchoolid");
			return (Criteria) this;
		}

		public Criteria andUSchoolidLessThan(Integer value) {
			addCriterion("u_schoolid <", value, "uSchoolid");
			return (Criteria) this;
		}

		public Criteria andUSchoolidLessThanOrEqualTo(Integer value) {
			addCriterion("u_schoolid <=", value, "uSchoolid");
			return (Criteria) this;
		}

		public Criteria andUSchoolidIn(List<Integer> values) {
			addCriterion("u_schoolid in", values, "uSchoolid");
			return (Criteria) this;
		}

		public Criteria andUSchoolidNotIn(List<Integer> values) {
			addCriterion("u_schoolid not in", values, "uSchoolid");
			return (Criteria) this;
		}

		public Criteria andUSchoolidBetween(Integer value1, Integer value2) {
			addCriterion("u_schoolid between", value1, value2, "uSchoolid");
			return (Criteria) this;
		}

		public Criteria andUSchoolidNotBetween(Integer value1, Integer value2) {
			addCriterion("u_schoolid not between", value1, value2, "uSchoolid");
			return (Criteria) this;
		}

		public Criteria andUInterestIdsIsNull() {
			addCriterion("u_interest_ids is null");
			return (Criteria) this;
		}

		public Criteria andUInterestIdsIsNotNull() {
			addCriterion("u_interest_ids is not null");
			return (Criteria) this;
		}

		public Criteria andUInterestIdsEqualTo(String value) {
			addCriterion("u_interest_ids =", value, "uInterestIds");
			return (Criteria) this;
		}

		public Criteria andUInterestIdsNotEqualTo(String value) {
			addCriterion("u_interest_ids <>", value, "uInterestIds");
			return (Criteria) this;
		}

		public Criteria andUInterestIdsGreaterThan(String value) {
			addCriterion("u_interest_ids >", value, "uInterestIds");
			return (Criteria) this;
		}

		public Criteria andUInterestIdsGreaterThanOrEqualTo(String value) {
			addCriterion("u_interest_ids >=", value, "uInterestIds");
			return (Criteria) this;
		}

		public Criteria andUInterestIdsLessThan(String value) {
			addCriterion("u_interest_ids <", value, "uInterestIds");
			return (Criteria) this;
		}

		public Criteria andUInterestIdsLessThanOrEqualTo(String value) {
			addCriterion("u_interest_ids <=", value, "uInterestIds");
			return (Criteria) this;
		}

		public Criteria andUInterestIdsLike(String value) {
			addCriterion("u_interest_ids like", value, "uInterestIds");
			return (Criteria) this;
		}

		public Criteria andUInterestIdsNotLike(String value) {
			addCriterion("u_interest_ids not like", value, "uInterestIds");
			return (Criteria) this;
		}

		public Criteria andUInterestIdsIn(List<String> values) {
			addCriterion("u_interest_ids in", values, "uInterestIds");
			return (Criteria) this;
		}

		public Criteria andUInterestIdsNotIn(List<String> values) {
			addCriterion("u_interest_ids not in", values, "uInterestIds");
			return (Criteria) this;
		}

		public Criteria andUInterestIdsBetween(String value1, String value2) {
			addCriterion("u_interest_ids between", value1, value2,
					"uInterestIds");
			return (Criteria) this;
		}

		public Criteria andUInterestIdsNotBetween(String value1, String value2) {
			addCriterion("u_interest_ids not between", value1, value2,
					"uInterestIds");
			return (Criteria) this;
		}

		public Criteria andUSkillIdsIsNull() {
			addCriterion("u_skill_ids is null");
			return (Criteria) this;
		}

		public Criteria andUSkillIdsIsNotNull() {
			addCriterion("u_skill_ids is not null");
			return (Criteria) this;
		}

		public Criteria andUSkillIdsEqualTo(String value) {
			addCriterion("u_skill_ids =", value, "uSkillIds");
			return (Criteria) this;
		}

		public Criteria andUSkillIdsNotEqualTo(String value) {
			addCriterion("u_skill_ids <>", value, "uSkillIds");
			return (Criteria) this;
		}

		public Criteria andUSkillIdsGreaterThan(String value) {
			addCriterion("u_skill_ids >", value, "uSkillIds");
			return (Criteria) this;
		}

		public Criteria andUSkillIdsGreaterThanOrEqualTo(String value) {
			addCriterion("u_skill_ids >=", value, "uSkillIds");
			return (Criteria) this;
		}

		public Criteria andUSkillIdsLessThan(String value) {
			addCriterion("u_skill_ids <", value, "uSkillIds");
			return (Criteria) this;
		}

		public Criteria andUSkillIdsLessThanOrEqualTo(String value) {
			addCriterion("u_skill_ids <=", value, "uSkillIds");
			return (Criteria) this;
		}

		public Criteria andUSkillIdsLike(String value) {
			addCriterion("u_skill_ids like", value, "uSkillIds");
			return (Criteria) this;
		}

		public Criteria andUSkillIdsNotLike(String value) {
			addCriterion("u_skill_ids not like", value, "uSkillIds");
			return (Criteria) this;
		}

		public Criteria andUSkillIdsIn(List<String> values) {
			addCriterion("u_skill_ids in", values, "uSkillIds");
			return (Criteria) this;
		}

		public Criteria andUSkillIdsNotIn(List<String> values) {
			addCriterion("u_skill_ids not in", values, "uSkillIds");
			return (Criteria) this;
		}

		public Criteria andUSkillIdsBetween(String value1, String value2) {
			addCriterion("u_skill_ids between", value1, value2, "uSkillIds");
			return (Criteria) this;
		}

		public Criteria andUSkillIdsNotBetween(String value1, String value2) {
			addCriterion("u_skill_ids not between", value1, value2, "uSkillIds");
			return (Criteria) this;
		}

		public Criteria andUIndustryIdIsNull() {
			addCriterion("u_industry_id is null");
			return (Criteria) this;
		}

		public Criteria andUIndustryIdIsNotNull() {
			addCriterion("u_industry_id is not null");
			return (Criteria) this;
		}

		public Criteria andUIndustryIdEqualTo(Integer value) {
			addCriterion("u_industry_id =", value, "uIndustryId");
			return (Criteria) this;
		}

		public Criteria andUIndustryIdNotEqualTo(Integer value) {
			addCriterion("u_industry_id <>", value, "uIndustryId");
			return (Criteria) this;
		}

		public Criteria andUIndustryIdGreaterThan(Integer value) {
			addCriterion("u_industry_id >", value, "uIndustryId");
			return (Criteria) this;
		}

		public Criteria andUIndustryIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("u_industry_id >=", value, "uIndustryId");
			return (Criteria) this;
		}

		public Criteria andUIndustryIdLessThan(Integer value) {
			addCriterion("u_industry_id <", value, "uIndustryId");
			return (Criteria) this;
		}

		public Criteria andUIndustryIdLessThanOrEqualTo(Integer value) {
			addCriterion("u_industry_id <=", value, "uIndustryId");
			return (Criteria) this;
		}

		public Criteria andUIndustryIdIn(List<Integer> values) {
			addCriterion("u_industry_id in", values, "uIndustryId");
			return (Criteria) this;
		}

		public Criteria andUIndustryIdNotIn(List<Integer> values) {
			addCriterion("u_industry_id not in", values, "uIndustryId");
			return (Criteria) this;
		}

		public Criteria andUIndustryIdBetween(Integer value1, Integer value2) {
			addCriterion("u_industry_id between", value1, value2, "uIndustryId");
			return (Criteria) this;
		}

		public Criteria andUIndustryIdNotBetween(Integer value1, Integer value2) {
			addCriterion("u_industry_id not between", value1, value2,
					"uIndustryId");
			return (Criteria) this;
		}

		public Criteria andUIntroduceIsNull() {
			addCriterion("u_introduce is null");
			return (Criteria) this;
		}

		public Criteria andUIntroduceIsNotNull() {
			addCriterion("u_introduce is not null");
			return (Criteria) this;
		}

		public Criteria andUIntroduceEqualTo(String value) {
			addCriterion("u_introduce =", value, "uIntroduce");
			return (Criteria) this;
		}

		public Criteria andUIntroduceNotEqualTo(String value) {
			addCriterion("u_introduce <>", value, "uIntroduce");
			return (Criteria) this;
		}

		public Criteria andUIntroduceGreaterThan(String value) {
			addCriterion("u_introduce >", value, "uIntroduce");
			return (Criteria) this;
		}

		public Criteria andUIntroduceGreaterThanOrEqualTo(String value) {
			addCriterion("u_introduce >=", value, "uIntroduce");
			return (Criteria) this;
		}

		public Criteria andUIntroduceLessThan(String value) {
			addCriterion("u_introduce <", value, "uIntroduce");
			return (Criteria) this;
		}

		public Criteria andUIntroduceLessThanOrEqualTo(String value) {
			addCriterion("u_introduce <=", value, "uIntroduce");
			return (Criteria) this;
		}

		public Criteria andUIntroduceLike(String value) {
			addCriterion("u_introduce like", value, "uIntroduce");
			return (Criteria) this;
		}

		public Criteria andUIntroduceNotLike(String value) {
			addCriterion("u_introduce not like", value, "uIntroduce");
			return (Criteria) this;
		}

		public Criteria andUIntroduceIn(List<String> values) {
			addCriterion("u_introduce in", values, "uIntroduce");
			return (Criteria) this;
		}

		public Criteria andUIntroduceNotIn(List<String> values) {
			addCriterion("u_introduce not in", values, "uIntroduce");
			return (Criteria) this;
		}

		public Criteria andUIntroduceBetween(String value1, String value2) {
			addCriterion("u_introduce between", value1, value2, "uIntroduce");
			return (Criteria) this;
		}

		public Criteria andUIntroduceNotBetween(String value1, String value2) {
			addCriterion("u_introduce not between", value1, value2,
					"uIntroduce");
			return (Criteria) this;
		}

		public Criteria andUPostAmountIsNull() {
			addCriterion("u_post_amount is null");
			return (Criteria) this;
		}

		public Criteria andUPostAmountIsNotNull() {
			addCriterion("u_post_amount is not null");
			return (Criteria) this;
		}

		public Criteria andUPostAmountEqualTo(Integer value) {
			addCriterion("u_post_amount =", value, "uPostAmount");
			return (Criteria) this;
		}

		public Criteria andUPostAmountNotEqualTo(Integer value) {
			addCriterion("u_post_amount <>", value, "uPostAmount");
			return (Criteria) this;
		}

		public Criteria andUPostAmountGreaterThan(Integer value) {
			addCriterion("u_post_amount >", value, "uPostAmount");
			return (Criteria) this;
		}

		public Criteria andUPostAmountGreaterThanOrEqualTo(Integer value) {
			addCriterion("u_post_amount >=", value, "uPostAmount");
			return (Criteria) this;
		}

		public Criteria andUPostAmountLessThan(Integer value) {
			addCriterion("u_post_amount <", value, "uPostAmount");
			return (Criteria) this;
		}

		public Criteria andUPostAmountLessThanOrEqualTo(Integer value) {
			addCriterion("u_post_amount <=", value, "uPostAmount");
			return (Criteria) this;
		}

		public Criteria andUPostAmountIn(List<Integer> values) {
			addCriterion("u_post_amount in", values, "uPostAmount");
			return (Criteria) this;
		}

		public Criteria andUPostAmountNotIn(List<Integer> values) {
			addCriterion("u_post_amount not in", values, "uPostAmount");
			return (Criteria) this;
		}

		public Criteria andUPostAmountBetween(Integer value1, Integer value2) {
			addCriterion("u_post_amount between", value1, value2, "uPostAmount");
			return (Criteria) this;
		}

		public Criteria andUPostAmountNotBetween(Integer value1, Integer value2) {
			addCriterion("u_post_amount not between", value1, value2,
					"uPostAmount");
			return (Criteria) this;
		}

		public Criteria andUActAmountIsNull() {
			addCriterion("u_act_amount is null");
			return (Criteria) this;
		}

		public Criteria andUActAmountIsNotNull() {
			addCriterion("u_act_amount is not null");
			return (Criteria) this;
		}

		public Criteria andUActAmountEqualTo(Integer value) {
			addCriterion("u_act_amount =", value, "uActAmount");
			return (Criteria) this;
		}

		public Criteria andUActAmountNotEqualTo(Integer value) {
			addCriterion("u_act_amount <>", value, "uActAmount");
			return (Criteria) this;
		}

		public Criteria andUActAmountGreaterThan(Integer value) {
			addCriterion("u_act_amount >", value, "uActAmount");
			return (Criteria) this;
		}

		public Criteria andUActAmountGreaterThanOrEqualTo(Integer value) {
			addCriterion("u_act_amount >=", value, "uActAmount");
			return (Criteria) this;
		}

		public Criteria andUActAmountLessThan(Integer value) {
			addCriterion("u_act_amount <", value, "uActAmount");
			return (Criteria) this;
		}

		public Criteria andUActAmountLessThanOrEqualTo(Integer value) {
			addCriterion("u_act_amount <=", value, "uActAmount");
			return (Criteria) this;
		}

		public Criteria andUActAmountIn(List<Integer> values) {
			addCriterion("u_act_amount in", values, "uActAmount");
			return (Criteria) this;
		}

		public Criteria andUActAmountNotIn(List<Integer> values) {
			addCriterion("u_act_amount not in", values, "uActAmount");
			return (Criteria) this;
		}

		public Criteria andUActAmountBetween(Integer value1, Integer value2) {
			addCriterion("u_act_amount between", value1, value2, "uActAmount");
			return (Criteria) this;
		}

		public Criteria andUActAmountNotBetween(Integer value1, Integer value2) {
			addCriterion("u_act_amount not between", value1, value2,
					"uActAmount");
			return (Criteria) this;
		}

		public Criteria andUStudentNumberIsNull() {
			addCriterion("u_student_number is null");
			return (Criteria) this;
		}

		public Criteria andUStudentNumberIsNotNull() {
			addCriterion("u_student_number is not null");
			return (Criteria) this;
		}

		public Criteria andUStudentNumberEqualTo(String value) {
			addCriterion("u_student_number =", value, "uStudentNumber");
			return (Criteria) this;
		}

		public Criteria andUStudentNumberNotEqualTo(String value) {
			addCriterion("u_student_number <>", value, "uStudentNumber");
			return (Criteria) this;
		}

		public Criteria andUStudentNumberGreaterThan(String value) {
			addCriterion("u_student_number >", value, "uStudentNumber");
			return (Criteria) this;
		}

		public Criteria andUStudentNumberGreaterThanOrEqualTo(String value) {
			addCriterion("u_student_number >=", value, "uStudentNumber");
			return (Criteria) this;
		}

		public Criteria andUStudentNumberLessThan(String value) {
			addCriterion("u_student_number <", value, "uStudentNumber");
			return (Criteria) this;
		}

		public Criteria andUStudentNumberLessThanOrEqualTo(String value) {
			addCriterion("u_student_number <=", value, "uStudentNumber");
			return (Criteria) this;
		}

		public Criteria andUStudentNumberLike(String value) {
			addCriterion("u_student_number like", value, "uStudentNumber");
			return (Criteria) this;
		}

		public Criteria andUStudentNumberNotLike(String value) {
			addCriterion("u_student_number not like", value, "uStudentNumber");
			return (Criteria) this;
		}

		public Criteria andUStudentNumberIn(List<String> values) {
			addCriterion("u_student_number in", values, "uStudentNumber");
			return (Criteria) this;
		}

		public Criteria andUStudentNumberNotIn(List<String> values) {
			addCriterion("u_student_number not in", values, "uStudentNumber");
			return (Criteria) this;
		}

		public Criteria andUStudentNumberBetween(String value1, String value2) {
			addCriterion("u_student_number between", value1, value2,
					"uStudentNumber");
			return (Criteria) this;
		}

		public Criteria andUStudentNumberNotBetween(String value1, String value2) {
			addCriterion("u_student_number not between", value1, value2,
					"uStudentNumber");
			return (Criteria) this;
		}

		public Criteria andUStudentPassIsNull() {
			addCriterion("u_student_pass is null");
			return (Criteria) this;
		}

		public Criteria andUStudentPassIsNotNull() {
			addCriterion("u_student_pass is not null");
			return (Criteria) this;
		}

		public Criteria andUStudentPassEqualTo(String value) {
			addCriterion("u_student_pass =", value, "uStudentPass");
			return (Criteria) this;
		}

		public Criteria andUStudentPassNotEqualTo(String value) {
			addCriterion("u_student_pass <>", value, "uStudentPass");
			return (Criteria) this;
		}

		public Criteria andUStudentPassGreaterThan(String value) {
			addCriterion("u_student_pass >", value, "uStudentPass");
			return (Criteria) this;
		}

		public Criteria andUStudentPassGreaterThanOrEqualTo(String value) {
			addCriterion("u_student_pass >=", value, "uStudentPass");
			return (Criteria) this;
		}

		public Criteria andUStudentPassLessThan(String value) {
			addCriterion("u_student_pass <", value, "uStudentPass");
			return (Criteria) this;
		}

		public Criteria andUStudentPassLessThanOrEqualTo(String value) {
			addCriterion("u_student_pass <=", value, "uStudentPass");
			return (Criteria) this;
		}

		public Criteria andUStudentPassLike(String value) {
			addCriterion("u_student_pass like", value, "uStudentPass");
			return (Criteria) this;
		}

		public Criteria andUStudentPassNotLike(String value) {
			addCriterion("u_student_pass not like", value, "uStudentPass");
			return (Criteria) this;
		}

		public Criteria andUStudentPassIn(List<String> values) {
			addCriterion("u_student_pass in", values, "uStudentPass");
			return (Criteria) this;
		}

		public Criteria andUStudentPassNotIn(List<String> values) {
			addCriterion("u_student_pass not in", values, "uStudentPass");
			return (Criteria) this;
		}

		public Criteria andUStudentPassBetween(String value1, String value2) {
			addCriterion("u_student_pass between", value1, value2,
					"uStudentPass");
			return (Criteria) this;
		}

		public Criteria andUStudentPassNotBetween(String value1, String value2) {
			addCriterion("u_student_pass not between", value1, value2,
					"uStudentPass");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table u_user
	 * @mbggenerated  Thu Jul 09 10:07:06 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table u_user
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 08 08:24:31 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}